# ~/.bashrc: executed by bash(1) for non-login shells.

# If not running interactively, don't do anything
case $- in
    *i*) ;;
      *) return;;
esac

# Load ble.sh (autosuggestions, syntax highlighting, completion menu).
# Attach it at the end of this file, after all other settings.
[[ -f ~/.local/share/blesh/ble.sh ]] && source ~/.local/share/blesh/ble.sh --attach=none

################# ENVIRONMENT ######################

export PATH="$HOME/.terragrunt/bin:$PATH"
export PATH="$HOME/.local/bin:$PATH"
export PATH="${ASDF_DATA_DIR:-$HOME/.asdf}/shims:$PATH"

export EDITOR=vim

# kubectl flag shortcuts, for example: k run nginx --image nginx $dry
export dry="--dry-run=client -o yaml"
export now="--force --grace-period 0"

################# HISTORY ######################

# don't put duplicate lines or lines starting with space in the history.
HISTCONTROL=ignoreboth

# append to the history file, don't overwrite it
shopt -s histappend

# History size
HISTSIZE=100000
HISTFILESIZE=100000

# Share the history between all open terminals.
# ble.sh does this with "bleopt history_share" (see ~/.blerc).
if [[ ! ${BLE_VERSION-} ]]; then
    PROMPT_COMMAND="history -a; history -n${PROMPT_COMMAND:+; $PROMPT_COMMAND}"
fi

# check the window size after each command and, if necessary,
# update the values of LINES and COLUMNS.
shopt -s checkwinsize

# match all files and zero or more directories and subdirectories.
shopt -s globstar

# make less more friendly for non-text input files, see lesspipe(1)
[ -x /usr/bin/lesspipe ] && eval "$(SHELL=/bin/sh lesspipe)"

################# PROMPT ######################

# Show the git branch, and "*" (unstaged) or "+" (staged) for changes
source /usr/lib/git-core/git-sh-prompt
GIT_PS1_SHOWDIRTYSTATE=1

# Line 1: full path, git branch. Line 2: " ➜ "
PS1='\[\e[01;32m\]${PWD}\[\e[00m\]$(__git_ps1 " git:(%s)")\n ➜ '

# If this is an xterm set the title to user@host:dir
case "$TERM" in
xterm*|rxvt*)
    PS1="\[\e]0;\u@\h: \w\a\]$PS1"
    ;;
*)
    ;;
esac

################# ALIASES ######################

# enable color support of ls and also add handy aliases
if [ -x /usr/bin/dircolors ]; then
    test -r ~/.dircolors && eval "$(dircolors -b ~/.dircolors)" || eval "$(dircolors -b)"
    alias ls='ls --color=auto'

    alias grep='grep --color=auto'
fi

# Alias definitions.
if [ -f ~/.bash_aliases ]; then
    . ~/.bash_aliases
fi

################# COMPLETION ######################

# enable programmable completion
if ! shopt -oq posix; then
  if [ -f /usr/share/bash-completion/bash_completion ]; then
    . /usr/share/bash-completion/bash_completion
  elif [ -f /etc/bash_completion ]; then
    . /etc/bash_completion
  fi
fi

complete -o nospace -C /usr/local/bin/terragrunt terragrunt

################# TOOLS ######################

eval "$(zoxide init bash)"

# Attach ble.sh last, so that it sees all the settings above
[[ ! ${BLE_VERSION-} ]] || ble-attach
